baseURL: https://zackhl.com # Ensure this is the correct domain for the consultancy

languageCode: en-us
title: "Zack Bai Consulting"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site - update if different for consultancy or remove if not public
  gitRepo: https://github.com/long765673/personal-site

  # specify whether you want to write some blog posts or not
  enableBlogPost: false # Changed to false for a consultancy focus

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true # Keep true for any detailed pages like case studies if added

  # Sections configuration
  sections:
    - id: about
    - id: experiences
    - id: skills
    # - id: projects # Assuming projects section is not yet created or enabled
    - id: hobbies
    # - id: achievements # Assuming achievements section is not yet created or enabled
    # - id: recent-posts # Disabled as enableBlogPost is false
    # - id: contact # Assuming contact section will be added later

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

