name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Update to v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Add Node.js setup
        with:
          node-version: '20' # Specify Node.js version (LTS recommended)
          cache: 'npm' # Cache npm dependencies

      - name: Install Node.js dependencies
        run: npm ci # Use ci for cleaner installs with package-lock.json

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # old version: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true # Ensure extended version is used for SCSS

      - name: Build
        run: hugo --minify # Build the site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
